// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzG5_NPRlSxQm8uTER4s3QEsZadqB1j1g',
    appId: '1:804159404946:web:f935c7b5b2c77eea215f4b',
    messagingSenderId: '804159404946',
    projectId: 'mexflis',
    authDomain: 'mexflis.firebaseapp.com',
    storageBucket: 'mexflis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcPbqi1SM6Ir4FuIbq56v1dAj4G-_onGw',
    appId: '1:804159404946:android:03f63e52a89d9a0c215f4b',
    messagingSenderId: '804159404946',
    projectId: 'mexflis',
    storageBucket: 'mexflis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPn2hKRHdFwOK7Vf1mZ0JM_rja0_9fvmE',
    appId: '1:804159404946:ios:9af0c0bb072dd3d1215f4b',
    messagingSenderId: '804159404946',
    projectId: 'mexflis',
    storageBucket: 'mexflis.appspot.com',
    iosClientId: '804159404946-f8t1gvujg4j4gs53eqnrrr9dsu868sse.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginCatalogo',
  );
}
